/* Generated by Together */

#ifndef AUDIOINPUT_H
#define AUDIOINPUT_H

#include <semaphore.h>
#include "TimeInfo.h"

#define AUDIOINPUT_TRACE	9
//!  Audio input buffer
/*!
  This class is the audio input buffer of a mixer InputStreams
*/

class AudioInput {
public:

	//! Default constructor
	/*!
	 * 	Initialise the buffer
	 */
    AudioInput();

    //! Destructor
    /*
     *	Cleanly disposes of the buffer
     */
    virtual ~AudioInput();

    //! Access the timing information
    /*!
     * This method returns the timestamp for the data contained in the buffer. The data is used by the synchonization manager to mix the streams 
     */
    virtual TimeInfo fetchTimeInfo();

    //! Changes the data contained in the buffer
    /*!
     * This method changes the data contained in the buffer. Buffer access is protected to prevent simultanious access.
     * 
     * \param data a pointer to a data buffer
     * \param size the size of the buffer
     */
    virtual void putData(short *data, int size, int timeStamp);

    //! Access the data contained the the buffer
    /*!
     * This method returns the data. Buffer access is protected to prevent simultanious access.
     * 
     * \param data a pointer to where the data must be copied
     * \return the size of the fetched data 
     */
    virtual int fetchData(short *data);

	//! Method to get the current size of the buffer
	/*!
	 * \return the size of the current internal buffer
	 */	 
    virtual int getSizeBuffer();

private:
	
	//! Fetch protection 
    sem_t sem_fetchData;
    
    //! Put protection
    sem_t sem_putData;
    
    //! Internal data buffer
    short * buffer;
    
    //! TimesStamp info
    TimeInfo* infoTemps;
    
    //! Data size
    int sizeBuffer;
    
};
#endif //AUDIOINPUT_H
