/* Generated by Together */

#include "AudioInput.h"
#include "TimeInfo.h"
#include <string.h>

void AudioInput::putData(int16 *data, int size, int leTemps)
{
  if (data!=NULL && size>0)
  {
    sem_wait(&semaphore);
    buffer = new int16[size];
    infoTemps = new TimeInfo(leTemps);
    memcpy(data,buffer,size);
    sizeBuffer=size;
    sem_post(&semaphore);
  }
}

int AudioInput::fetchData(int16 *data) 
{ 
  if (buffer!=NULL && data!=NULL)
  {
    sem_wait(&semaphore);
    memcpy(buffer,data,sizeBuffer);
    sem_post(&semaphore);
    return 0;
  }
  else
    return 1;
}

int AudioInput::getSizeBuffer()
{
  int leSize;
  sem_wait(&semaphore);
  leSize = sizeBuffer;
  sem_post(&semaphore);
  return leSize;
}

AudioInput::AudioInput()
{
  sem_init(&semaphore,0,1);
  buffer=NULL;
  infoTemps=NULL;
  sizeBuffer=0;
}

AudioInput::~AudioInput()
{
  if (buffer!=NULL){
    delete []buffer;
    buffer=NULL;
  }
  if (infoTemps!=NULL){
    delete infoTemps;
    infoTemps=NULL;
  }
  sem_destroy(&semaphore);
}

void AudioInput::putTimeInfo(TimeInfo* infos)
{
  sem_wait(&semaphore);
  infoTemps = infos;
  sem_post(&semaphore);
}

TimeInfo AudioInput::fetchTimeInfo()
{
  TimeInfo* leTemps;
  sem_wait(&semaphore);
  leTemps = infoTemps;
  sem_post(&semaphore);
  return (*leTemps);
}

