/* Generated by Together */

#include "AudioOuput.h"
#include "../tracePrintSFL.h"


int AudioOuput::fetchData(short *data)
{ 
  if (buffer!=NULL && data!=NULL)
  {
    ptracesfl("AudioOuput - fetchData(): Demande semaphore",MT_INFO,true);
    sem_wait(&semaphore);
    ptracesfl("AudioOuput - fetchData(): Zone Critique",MT_INFO,true);
    memcpy(buffer,data,sizeBuffer);
    sem_post(&semaphore);
    ptracesfl("AudioOuput - fetchData(): Sortie Zone Critique",MT_INFO,true);
    return 0;
  }
  else
  {
    ptracesfl("AudioOuput - fetchData(): Erreur parametre",MT_ERROR,true);
    return 1;
  }
}

void AudioOuput::putData(short * data, int size)
{ 
  if (data!=NULL && size>0)
  {
    ptracesfl("AudioOuput - putData(): Demande semaphore",MT_INFO,true);
    sem_wait(&semaphore);
    ptracesfl("AudioOuput - putData(): Zone Critique",MT_INFO,true);
    buffer = new short[size]; 
    memcpy(data,buffer,size);
    sizeBuffer=size;
    sem_post(&semaphore);
    ptracesfl("AudioOuput - putData(): Sortie Zone Critique",MT_INFO,true);
  }
  else
    ptracesfl("AudioOuput - putData(): Erreur parametre",MT_ERROR,true);
}

AudioOuput::AudioOuput()
{
  ptracesfl("AudioOuput - AudioOuput(): Creation de l'objet",MT_INFO,true);
  sem_init(&semaphore,0,1);
  buffer=NULL;
  sizeBuffer=0;
}

AudioOuput::~AudioOuput()
{
  ptracesfl("AudioOuput - ~AudioOuput(): Destruction de l'objet",MT_INFO,true);
  if (buffer!=NULL){
    delete []buffer;
    buffer=NULL;
  }
  sem_destroy(&semaphore);
}

// DEPRECIATED !!!!!
int AudioOuput::fetchData(char* data)
{
  return 0; 
}
// DEPRECIATED !!!!!
void AudioOuput::putData(char * data, int size)
{ 
  
}
