/* Generated by Together */

#include "InputStreams.h"
#include "VideoInput.h"
#include "AudioInput.h"
#include "../tracePrintSFL.h"

InputStreams::InputStreams()
{
  audioInput = NULL;
  videoInput = NULL;
}

InputStreams::InputStreams(VideoInput* videoData, AudioInput* audioData)
{
  audioInput = audioData;
  videoInput = videoData;
}

InputStreams::~InputStreams()
{
  delete audioInput;
  delete videoInput;
}

VideoInput* InputStreams::fetchVideoStream() const
{
  return videoInput;
}

AudioInput* InputStreams::fetchAudioStream() const
{
  return audioInput;
}
