/* Generated by Together */

#include "InternalBuffer.h"
#include <string.h>
#include <stdlib.h>
#include "../tracePrintSFL.h"

bool InternalBuffer::putData(void * data, int size)
{
  if (data!=NULL && size > 0)
  {
    if( buffer != NULL )
    	free( buffer);
    buffer = (void*) malloc(size);
    memcpy(buffer,data,size);
    sizeBuffer=size;
    ptracesfl("InternalBuffer - Sending signal of new data",MT_INFO, INTERNALBUFFER_TRACE);
    sem_post(&semaphore);
    return true;
  }
  else
  {
    if( data == NULL )
  		ptracesfl("InternalBuffer - fetchData(): bad paramteter",MT_ERROR, INTERNALBUFFER_TRACE);
  	else
    	ptracesfl("InternalBuffer - fetchData(): empty buffer",MT_ERROR, INTERNALBUFFER_TRACE);
    return false;
  }
}

bool InternalBuffer::fetchData(void * data)
{
  if (buffer!=NULL && data!=NULL)
  {
  	ptracesfl("InternalBuffer - watting for new data",MT_INFO, INTERNALBUFFER_TRACE);
    sem_wait(&semaphore);
    ptracesfl("InternalBuffer - recieved new data",MT_INFO, INTERNALBUFFER_TRACE);
    memcpy(data, buffer,sizeBuffer);
    return true;
  }
  else
  {
   	if( data == NULL )
  		ptracesfl("InternalBuffer - fetchData(): bad paramteter",MT_ERROR, INTERNALBUFFER_TRACE);
  	else
    	ptracesfl("InternalBuffer - fetchData(): empty buffer",MT_ERROR, INTERNALBUFFER_TRACE);
    return false;
  }
}

int InternalBuffer::getSizeBuffer()
{
   return this->sizeBuffer;
}

InternalBuffer::InternalBuffer()
{
  sem_init(&semaphore,0,0);
  buffer= NULL;
  sizeBuffer= 0;
}

InternalBuffer::~InternalBuffer()
{
  if (buffer!=NULL)
    free(buffer);
}

void InternalBuffer::Init()
{
  //TODO: humm...
}
