/* Generated by Together */

#include "LocalVideoOuput.h"

void LocalVideoOuput::putData(char * data, int size)
{   
}

void LocalVideoOuput::putData(char * data, int size, MemKey *localVideoMemKey, int width, int height)
{
    
  // put data into a new memSpace

  if(!this->manager->putData(localVideoMemKey, (unsigned char*)data, size, width, height)){
  	ptracesfl("LocalVideoOutput - Can't put data", MT_ERROR, true);
  }

}

LocalVideoOuput::LocalVideoOuput()
{
  // create the manager (or get the instance)
  this->manager = MemManager::getInstance();
}

LocalVideoOuput::~LocalVideoOuput()
{
  
}

// This method is not used in this class
int LocalVideoOuput::fetchData(char* data)
{
  return 0;
}
