/* Generated by Together */

#include "LocalAudioOuput.h"
#include "../tracePrintSFL.h"
#include "../manager.h"


void LocalAudioOuput::putData(short * data, int size)
{
	// play audio (put data in speakers)
	printf("\n LocalAudioOuput  :  putData : playSample\n");
	audioLayer->playSamples(/*toAudioLayer*/ data, size /*nbSample * sizeof(SFLDataFormat)*/);
}

LocalAudioOuput::LocalAudioOuput()
{
//printf(" LocalAudioOuput  :  Constructor\n");
	// init the audioDevice (audioLayer)
	audioLayer = Manager::instance().getAudioDriver();
	if (!audioLayer){
		ptracesfl("LocalAudioOutput - Constructor error : init AudioLayer error!",MT_ERROR,true);
	}
}

LocalAudioOuput::~LocalAudioOuput()
{
	//TODO : delete audiolayer and all free used memory
}

// This method is not used in this class
int LocalAudioOuput::fetchData(short *data)
{
	return 0;
}