/* Generated by Together */

#include "LocalAudioOuput.h"


int LocalAudioOuput::fetchData(short *data)
{ 
  return 0;
}

void LocalAudioOuput::putData(short * data, int size)
{ 
  
}

LocalAudioOuput::LocalAudioOuput()
{
  
}

LocalAudioOuput::~LocalAudioOuput()
{
  
}
