/* Generated by Together */

#include "NoSynch.h"
#include "../tracePrintSFL.h"


void NoSynch::run()
{
  OkToKill = false;
  while(Active)
  {
    ptracesfl("NoSynch - run(): Tente de copier des donnees",MT_INFO,true); 
    //Recuperation des Stream Audio et Video
    audioInput = inputStreams->fetchAudioStream();
    videoInput = inputStreams->fetchVideoStream();

    //Recuperation des grandeurs pour les datas audio/video
    sizeBufferAudio=audioInput->getSizeBuffer();
    sizeBufferVideo=videoInput->getSizeBuffer();

    //Creation des datas audio/video
    dataAudio = new int16[sizeBufferAudio];
    dataVideo = new char[sizeBufferVideo];

    // Recuperation des donnes Audio et Video
    audioInput->fetchData(dataAudio);
    videoInput->fetchData(dataVideo);

    //Depot dans les buffers internes audio/video
    if (!bufferAudio->putData((void*)dataAudio,sizeBufferAudio))
      ;//"Impossible de déposer les donnes dans le buffer audio interne"
    if (!bufferVideo->putData((void*)dataVideo,sizeBufferVideo))
      ;//"Impossible de déposer les donnes dans le buffer audio interne"

    delete dataAudio;
    delete dataVideo;
  }
  ptracesfl("NoSynch - run(): Le thread travail plus :(",MT_INFO,true);
  OkToKill=true;
}

void NoSynch::stop()
{
  ptracesfl("NoSynch - stop(): Demande d'arret recu...",MT_INFO,true);
  Active=false;
  while(!OkToKill);
  ptracesfl("NoSynch - stop(): Killing Thread now!",MT_INFO,true);
}

NoSynch::~NoSynch()
{
  ptracesfl("NoSynch - ~NoSynch(): Destruction de l'objet",MT_INFO,true);
  if (dataAudio!=NULL)
    delete dataAudio;
  if (dataVideo!=NULL)
    delete dataVideo;
}

NoSynch::NoSynch(InputStreams* Streams, InternalBuffer* video, InternalBuffer* audio)
{
  ptracesfl("NoSynch - NoSynch(): Creation de l'objet",MT_INFO,true);
  inputStreams = Streams;
  bufferAudio = audio;
  bufferVideo = video;
  Active=true;
  OkToKill=true;
}

NoSynch::NoSynch()
{
  // Deprecated
}
