/* Generated by Together */

#include "StraightThrough_VT.h"

StraightThrough_VT::StraightThrough_VT()
{
}

StraightThrough_VT::StraightThrough_VT(InternalBuffer* video,  OutputStream* output)
{
  inputBuffer = video;
  outputBuffer = output;
  Active=false;
  OkToKill=false;
}

StraightThrough_VT::~StraightThrough_VT()
{  
}

void StraightThrough_VT::run()
{ 
  Active=true;
  OkToKill=false;
  
  unsigned char* data= NULL;
 
  ptracesfl("StraightThrough_VT - pause(): Starting ...",MT_INFO,STRAIGHTTHROUGH_TRACE); 
  while(Active)
  {
  	
  	ptracesfl("StraightThrough_VT - run(): Getting internal video buffer size",MT_INFO,STRAIGHTTHROUGH_TRACE);
    int sizeBuffer = inputBuffer->getSizeBuffer();
    
    if( sizeBuffer != 0){
    	
    	ptracesfl("StraightThrough_VT - run(): Data Size is: %d",MT_INFO,STRAIGHTTHROUGH_TRACE, true, 1, sizeBuffer);

    	//data= new unsigned char[ sizeBuffer ];
    	
    	ptracesfl("StraightThrough_VT - run(): Fetching data from internal video buffer ...",MT_INFO,STRAIGHTTHROUGH_TRACE);
    	data = (unsigned char*)(inputBuffer->fetchData(sizeBuffer));
	    if( sizeBuffer != -1 ){
	    	ptracesfl("StraightThrough_VT - run(): Sending data to audio video buffer ...",MT_INFO,STRAIGHTTHROUGH_TRACE);
		    outputBuffer->putData(data,sizeBuffer);
	    }else{
   			ptracesfl("StraightThrough_VT - run(): Cannot fetch data from internal buffer",MT_ERROR,STRAIGHTTHROUGH_TRACE);
	    }
	    
	    data= NULL;
   			
    }else{
    	ptracesfl("StraightThrough_VT - run(): No Data to fetch", MT_WARNING, STRAIGHTTHROUGH_TRACE);
    	usleep(51);
    }
    
    // This thread must sleep longer than the sync thread to create a continious stream of information for the output.
    usleep(5);
  }
  
  ptracesfl("StraightThrough_VT - run(): The run thread has stopped cleanly",MT_INFO,STRAIGHTTHROUGH_TRACE);
  
  OkToKill=true;
}

void StraightThrough_VT::pause()
{ 
  ptracesfl("StraightThrough_VT - pause(): Pausing...",MT_INFO,true);
  
  OkToKill=false;
  Active=false;
  
  while(!OkToKill);
  
}

void StraightThrough_VT::restart()
{
  ptracesfl("StraightThrough_VT - restart(): Restarting...",MT_INFO,true);
  run();
}

void StraightThrough_VT::stop()
{ 
  ptracesfl("StraightThrough_VT - stop(): Stopping...",MT_INFO,true);
  
  OkToKill=false;
  Active=false;
    
  while(!OkToKill);
}

