/* Generated by Together */

#include "TimeInfo.h"


TimeInfo::TimeInfo()
{
  temps=0;
}

TimeInfo::TimeInfo(int infos)
{
  temps=infos;
}

int TimeInfo::getTemps()
{
  return temps;
}
