/* Generated by Together */

#ifndef VIDEOINPUT_H
#define VIDEOINPUT_H

#include <semaphore.h>
#include "TimeInfo.h"
#include <string.h>

#define VIDEOINPUT_TRACE	9

//!  Video input buffer
/*!
 * This class is the video input buffer of a mixer InputStreams
 */

class VideoInput {
public:

	//! Default Constructor
	/*!
	 * 	Initialise the buffer
	 */
    VideoInput();

    //! Destructor
    /*
     *	Cleanly disposes of the buffer
     */
    ~VideoInput();

    //! Access the data contained the the buffer
    /*!
     * This method returns the data. Buffer access is protected to prevent simultanious access.
     * 
     * \param data a pointer to where the data must be copied
     * \return the size of the fetched data 
     */
    virtual int fetchData(unsigned char* data, int &w, int &h);

    //! Access the timing information
    /*!
     * This method returns the timestamp for the data contained in the buffer. The data is used by the synchonization manager to mix the streams 
     */
    virtual TimeInfo fetchTimeInfo();

    //! Changes the data contained in the buffer
    /*!
     * This method changes the data contained in the buffer. Buffer access is protected to prevent simultanious access.
     * 
     * \param data a pointer to a data buffer
     * \param size the size of the buffer
     */
    virtual void putData(char * data, int size, int leTemps, int w, int h);

	//! Method to get the current size of the buffer
	/*!
	 * \return the size of the current internal buffer
	 */	 
    virtual int getSizeBuffer();

private:
	
	//! Fetch protection 
    sem_t sem_fetchData;
    
    //! Put protection
    sem_t sem_putData;
    
    //! Internal data buffer
    char * buffer;
    
    //! Timestamp info
    TimeInfo* infoTemps;
    
    //! Size of data
    int sizeBuffer;
    
    //! Width of the image contained in the data
    int width;
    
    //! Height of the image contained in the data
    int height;
    
};
#endif //VIDEOINPUT_H
