/* Generated by Together */

#ifndef SWSINTERFACE_H
#define SWSINTERFACE_H


#include <ffmpeg/avcodec.h>
#include <ffmpeg/swscale.h>
#include <stdlib.h>
#include <stdio.h>

 struct FrameProperties
    {
        int width;
        int height;
        int pixFormat;

    };
    
class SWSInterface {
public:
	/**
     * Default Destructor
     * 
     */
   ~SWSInterface();
  
   /**
     *  Constructor we force to use
     * 
     */
    
    SWSInterface(int InWidth,int InHeight,int InPixFormat,int OutWidth,int OutHeight,int OutPixFormat);
/**


    /**
  *  Function to change RGB to YUV420
  * */
    uint8_t *Convert(AVFrame *In,AVFrame *Out);

    FrameProperties getInputProperties();

    void setInputProperties(int setWidth,int setHeight,int setPixFormat);
    void setInputProperties(int setWidth,int setHeight);

    FrameProperties getOutputProperties();

    void setOutputProperties(int setWidth,int setHeight,int setPixFormat);
    void setOutputProperties(int setWidth,int setHeight);

private:

	SWSInterface();
	
	struct SwsContext *Context;
    /**
     * Libavcodec YUV buffer Size
     */
    int BufferSize;
    FrameProperties out;
    FrameProperties in;
     
};
#endif //SWSINTERFACE_H
