#ifndef VIDEOSETTINGS_H_
#define VIDEOSETTINGS_H_


#define VIDEO_BIT_RATE 2000
#define DEFAULT_WIDTH 640
#define DEFAULT_HEIGHT 480
#define STREAM_FRAME_RATE 10	
#define GOP_SIZE 12
#define MAX_B_FRAMES 1000

#endif /*VIDEOSETTINGS_H_*/
