#ifndef VIDEOSETTINGS_H_
#define VIDEOSETTINGS_H_


#define VIDEO_BIT_RATE 768000
#define DEFAULT_WIDTH 352
#define DEFAULT_HEIGHT 288
#define STREAM_FRAME_RATE 10
#define GOP_SIZE 8
#define MAX_B_FRAMES 0

#endif /*VIDEOSETTINGS_H_*/
