SFLPhoneVoicemailWebAgent: VMStorage Class Reference
VMStorage Class Reference
Public Member Functions
__construct ()
__destruct ()
delete ($folder, $vm)
deleteFolder ($folder)
getLstFolders ()
load ()
rename ($foldName, $oldName, $newName)
renameAll ($folder)
Protected Attributes
$lstFolders = array()
Detailed Description
class VMStorage
Definition at line 28 of file VMStorage.php.
Constructor & Destructor Documentation
VMStorage::__construct ()
VMStorageDB -- Constructor
Definition at line 36 of file VMStorage.php.
VMStorage::__destruct ()
VMStorageDB -- Destructor
Reimplemented in VMStorageFile, VMStorageIMAP, and VMStorageODBC.
Definition at line 43 of file VMStorage.php.
Member Function Documentation
VMStorage::delete ($ folder, $ vm) [abstract]
delete(a_voicemail_folder, a_voicemail)
Parameters:
string a_voicemail_folder
string a_voicemail_name
Returns:
bool
Reimplemented in VMStorageFile, VMStorageIMAP, and VMStorageODBC.
VMStorage::deleteFolder ($ folder) [abstract]
deleteFolder(a_voicemail_folder)
Parameters:
string a_voicemail_folder
Returns:
bool
Reimplemented in VMStorageFile, VMStorageIMAP, and VMStorageODBC.
VMStorage::getLstFolders ()
getLstFolders()
Returns:
Array<VoicemailFolde> lstFolders
Definition at line 90 of file VMStorage.php.
VMStorage::load () [abstract]
load()
Reimplemented in VMStorageFile, VMStorageIMAP, and VMStorageODBC.
VMStorage::rename ($ foldName, $ oldName, $ newName) [abstract]
rename(a_voicemail_folder, a_voicemail_old_name, a_voicemail_new_name)
Parameters:
string a_voicemail_folder
string a_voicemail_old_name
string a_voicemail_new_name
Returns:
bool
Reimplemented in VMStorageFile, VMStorageIMAP, and VMStorageODBC.
Referenced by renameAll().
VMStorage::renameAll ($ folder)
renameAll()
Returns:
bool
Definition at line 51 of file VMStorage.php.
References $lstFolders, and rename().
Member Data Documentation
VMStorage::$lstFolders = array() [protected]
Protected instance vars:
Definition at line 31 of file VMStorage.php.
Referenced by renameAll().
The documentation for this class was generated from the following file:
VMStorage.php