SFLPhoneVoicemailWebAgent: VoicemailFolder Class Reference
VoicemailFolder Class Reference
Public Member Functions
__construct ($name="")
__destruct ()
addVMail ($vm)
getCount ()
getListVM ()
getName ()
getVMByName ($newName)
rename ($oldName, $newName)
setName ($name)
toShortString ()
toString ()
Detailed Description
class VoicemailFolder
Definition at line 25 of file VoicemailFolder.php.
Constructor & Destructor Documentation
VoicemailFolder::__construct ($ name = "")
VoicemailFolder -- Constructor
Definition at line 34 of file VoicemailFolder.php.
VoicemailFolder::__destruct ()
VoicemailFolder -- Destructor
Definition at line 42 of file VoicemailFolder.php.
Member Function Documentation
VoicemailFolder::addVMail ($ vm)
addVMail(a_voicemail)
Parameters:
Voicemail a_voicemail
Definition at line 98 of file VoicemailFolder.php.
VoicemailFolder::getCount ()
getCount()
Returns:
int nb_of_voicemail
Definition at line 68 of file VoicemailFolder.php.
Referenced by toShortString(), and toString().
VoicemailFolder::getListVM ()
getListVM()
Returns:
array<Voicemail> list_of_voicemail
Definition at line 76 of file VoicemailFolder.php.
Referenced by getVMByName(), and rename().
VoicemailFolder::getName ()
getName()
Returns:
string folderName
Definition at line 60 of file VoicemailFolder.php.
Referenced by getVMByName(), rename(), toShortString(), and toString().
VoicemailFolder::getVMByName ($ newName)
getVMByName(a_voicemail_name)
Parameters:
string a_voicemail_name
Returns:
Voicemail the_searched_voicemail
Definition at line 85 of file VoicemailFolder.php.
References getListVM(), and getName().
VoicemailFolder::rename ($ oldName, $ newName)
rename(old_vm_name, new_vm_name)
Parameters:
string old_vm_name
string new_vm_name
Returns:
string result : "OK" if ok, a text message otherwise
Definition at line 108 of file VoicemailFolder.php.
References $arr, getListVM(), and getName().
VoicemailFolder::setName ($ name)
setName(name)
Parameters:
string name
Definition at line 52 of file VoicemailFolder.php.
VoicemailFolder::toShortString ()
toShortString()
Definition at line 125 of file VoicemailFolder.php.
References getCount(), and getName().
VoicemailFolder::toString ()
toString()
Definition at line 141 of file VoicemailFolder.php.
References getCount(), and getName().
The documentation for this class was generated from the following file:
VoicemailFolder.php