SFLPhoneVoicemailWebAgent: VMAuthFile Class Reference
VMAuthFile Class Reference
Public Member Functions
__construct ($login="", $pass="", $context="default", $file="/etc/asterisk/voicemail.conf")
__destruct ()
getContext ()
getLogin ()
getPass ()
login ()
logoff ()
setContext ($context)
setLogin ($login)
setPass ($pass)
Detailed Description
class VMAuthFile
Definition at line 27 of file VMAuthFile.php.
Constructor & Destructor Documentation
VMAuthFile::__construct ($ login = "", $ pass = "", $ context = "default", $ file = "/etc/asterisk/voicemail.conf")
VMAuthFile -- Constructor
Parameters:
string login
string password
string context ("default" by default)
string file_configuration ("/etc/asterisk/voicemail.conf" by default)
Definition at line 39 of file VMAuthFile.php.
References VMAuth::$context, VMAuth::$login, VMAuth::$pass, and login().
VMAuthFile::__destruct ()
VMAuthFile -- Destructor
Reimplemented from VMAuth.
Definition at line 49 of file VMAuthFile.php.
Member Function Documentation
VMAuthFile::getContext ()
getContext()
Returns:
associated context
Definition at line 57 of file VMAuthFile.php.
Referenced by login().
VMAuthFile::getLogin ()
getLogin()
Returns:
string login
Definition at line 73 of file VMAuthFile.php.
References login().
VMAuthFile::getPass ()
getPass()
Returns:
string password
Definition at line 89 of file VMAuthFile.php.
VMAuthFile::login ()
login()
Returns:
TRUE if well registered in $VOICEMAIL_CONF file (default is /etc/asterisk/voicemail.conf), FALSE otherwise
Saving current context
Matching current mailbox with own datas
Reimplemented from VMAuth.
Definition at line 105 of file VMAuthFile.php.
References getContext().
Referenced by __construct(), getLogin(), and setLogin().
VMAuthFile::logoff ()
logoff()
Returns:
always TRUE due to login method
Reimplemented from VMAuth.
Definition at line 144 of file VMAuthFile.php.
VMAuthFile::setContext ($ context)
setContext(a_context)
Parameters:
string a_context
Definition at line 65 of file VMAuthFile.php.
References VMAuth::$context.
VMAuthFile::setLogin ($ login)
setLogin(a_login)
Parameters:
string a_login
Definition at line 81 of file VMAuthFile.php.
References VMAuth::$login, and login().
VMAuthFile::setPass ($ pass)
setPass(a_password)
Parameters:
string a_password
Definition at line 97 of file VMAuthFile.php.
References VMAuth::$pass.
The documentation for this class was generated from the following file:
VMAuthFile.php