SFLPhoneVoicemailWebAgent: index.php File Reference
index.php File Reference
Variables
$agent = new VMAgent($login, $pass, $context)
$arr = explode("/", $path)
$context
$is_logged = $agent->login($login, $pass, $context)
$login
$pass = $_SERVER['PHP_AUTH_PW']
exit
Variable Documentation
$agent = new VMAgent($login, $pass, $context)
Definition at line 73 of file index.php.
$arr = explode("/", $path)
Definition at line 88 of file index.php.
Referenced by VMStorageFile::delete(), VMStorageFile::deleteFolder(), VMStorageFile::getSound(), VMStorageFile::load(), VoicemailFolder::rename(), and VMStorageFile::rename().
$context
Initial value:
 substr( $_SERVER['PHP_AUTH_USER'],
                                   0,
                                   strpos($_SERVER['PHP_AUTH_USER'], "-") )
Definition at line 65 of file index.php.
Referenced by VMAgent::__construct(), and VMAgent::login().
$is_logged = $agent->login($login, $pass, $context)
Definition at line 74 of file index.php.
$login
Initial value:
 substr( $_SERVER['PHP_AUTH_USER'],
                                   strpos($_SERVER['PHP_AUTH_USER'], "-")+1,
                                   strlen($_SERVER['PHP_AUTH_USER']) )
Definition at line 68 of file index.php.
Referenced by VMAgent::__construct(), and VMAgent::login().
$pass = $_SERVER['PHP_AUTH_PW']
Definition at line 71 of file index.php.
Referenced by VMAgent::__construct(), and VMAgent::login().
exit
Definition at line 24 of file index.php.