/* Generated by Together */

#include "Brightness.h"

  Brightness::Brightness(){}

  Brightness::~Brightness(){}

  bool Brightness::increase(__u16 value){

    __u16 currentValue = this->videoDevice->getVideoPicture()->brightness;
    
    if( (currentValue+value) > 65535 ){ // if the brightness value is already at its maximum
      return false; // indicate that the value is already at its maximum
    }
    else{
      this->videoDevice->setBrightness(currentValue+value);
      // ioctl call in VideoDevice to apply changes
      return this->videoDevice->applyChanges('p'); // indicate that the value has been increased and if ioctl has been correctly done (return true or false)
    }
    
  }

  bool Brightness::decrease(__u16 value){
    
    __u16 currentValue = this->videoDevice->getVideoPicture()->brightness;
    
    if( (currentValue-value) < 0 ){ // if the brightness value is already at its maximum
      return false; // indicate that the value is already at its maximum
    }
    else{
      this->videoDevice->setBrightness(currentValue-value);
      // ioctl call in VideoDevice to apply changes
      return this->videoDevice->applyChanges('p'); // indicate that the value has been decreased and if ioctl has been correctly done (return true or false)
    }
    
  }

  bool Brightness::setTo(__u16 value){
    this->videoDevice->setBrightness(value);
    // ioctl call in VideoDevice to apply changes
    return this->videoDevice->applyChanges('p'); // indicate that the value has been seted and if ioctl has been correctly done (return true or false)
  }

  bool Brightness::reset(){
    //\ TODO
    return true;
  }
  
  char* Brightness::getBrightness(){
    //\ TODO
    return 0;
  }

