/* Generated by Together */

#include "Brightness.h"

  Brightness::Brightness(){}

  Brightness::~Brightness(){}

  bool Brightness::increase(__u16 value){

    __u16 currentValue = this->videoDevice->getVideoPicture()->brightness;
    
    if( (currentValue+value) > 65535 ){ // if the brightness value is already at its maximum
      return false; // indicate that the value is already at its maximum
    }
    else{
      this->videoDevice->setBrightness(currentValue+value);
      return true; // indicate that the value has been increased
    }
    
  }

  bool Brightness::decrease(__u16 value){
    
    __u16 currentValue = this->videoDevice->getVideoPicture()->brightness;
    
    if( (currentValue-value) < 0 ){ // if the brightness value is already at its maximum
      return false; // indicate that the value is already at its maximum
    }
    else{
      this->videoDevice->setBrightness(currentValue-value);
      return true; // indicate that the value has been increased
    }
    
  }

  bool Brightness::setTo(__u16 value){

    return true;
  }

  bool Brightness::reset(){

    return true;
  }
  
  char* Brightness::getBrightness(){

    return 0;
  }

