/* Generated by Together */

#include "Capture.h"
#include "CaptureMode.h"

  Capture::Capture(){
  // TODO
  }

  Capture::~Capture(){
  // TODO
  }

  bool Capture::nextCaptureMode(){
    // TODO
  }

  bool Capture::forceCaptureMode(int captModePos){
// TODO
    return true;
  }

  void Capture::createCaptureModesVector(){
  // TODO
  }



  char* Capture::GetCapture(){
  	//\ TODO
    char* test;    

      *test = 't';

    return test;
  }
  
  
  

// These function are not used for this class

  bool Capture::decrease(int value){

    return true;
  }

  bool Capture::setTo(int value){

    return true;
  }

  bool Capture::reset(){

    return true;
  }

  bool Capture::increase(int value){

    return true;
  }
