/* Generated by Together */

#include "Colour.h"

  Colour::Colour(){}

  Colour::~Colour(){}

  bool Colour::increase(__u16 value){
  	
  	__u16 currentValue = this->videoDevice->getVideoPicture()->colour;
    
    if( (currentValue+value) > 65535 ){ // if the colour value is already at its maximum
      return false; // indicate that the value is already at its maximum
    }
    else{
      this->videoDevice->setColour(currentValue+value);
      // ioctl call in VideoDevice to apply changes
      return this->videoDevice->applyChanges('p'); // indicate that the value has been increased if ioctl has been correctly done (return true or false)
    }
    
  }

  bool Colour::decrease(__u16 value){
    
    __u16 currentValue = this->videoDevice->getVideoPicture()->colour;
    
    if( (currentValue-value) < 0 ){ // if the colour value is already at its maximum
      return false; // indicate that the value is already at its maximum
    }
    else{
      this->videoDevice->setColour(currentValue-value);
      // ioctl call in VideoDevice to apply changes
      return this->videoDevice->applyChanges('p'); // indicate that the value has been decreased if ioctl has been correctly done (return true or false)
    }
    
  }

  bool Colour::setTo(__u16 value){
    this->videoDevice->setColour(value);
    // ioctl call in VideoDevice to apply changes
    return this->videoDevice->applyChanges('p'); // indicate that the value has been seted if ioctl has been correctly done (return true or false)
  }

  bool Colour::reset(){
    //\ TODO
    return true;
  }
  
  char* Colour::getColour(){
    //\ TODO
    return 0;
  }
