/* Generated by Together */

#include "CopyMode.h"

  CopyMode::CopyMode(){
    	//\ TODO
  }

  CopyMode::~CopyMode(){
    	//\ TODO
  }

  char* CopyMode::capture(){
    	//\ TODO
    char* test;    

      *test = 't';

    return test;
  }

