/* Generated by Together */

#ifndef READMODE_H
#define READMODE_H
#include "CaptureMode.h"

//! CopyMode
/*!
 * This class capture from the video source using a read mode
 */
class ReadMode : public CaptureMode {
public:

    //! Constructor
    ReadMode(VideoDevice* device);

    //! Destructor
    ~ReadMode();
    
    //! Initializes the capture mode
    /*!
     * This method is called before the capture mode is used.
     */
    virtual bool init();
    
    //! Shuts down the capture mode
    /*!
     * This method is called when the captude mode changes for an other.
     */
    virtual bool close();

    //! Method to capture from the video source
    /*!
     * \return a pointer to the captured data
     */
     virtual char* capture();
     
protected:

     //! Default Constructor
    ReadMode();
};
#endif //READMODE_H
