/* Generated by Together */

#include "ReadMode.h"

  ReadMode::ReadMode(){
    	//\ TODO
  }

  ReadMode::~ReadMode(){
    	//\ TODO
  }

  char* ReadMode::capture(){
  	
  	  	//\ TODO
    char* test;    

      *test = 't';

    return test;
  }
