/* Generated by Together */

#include "Resolution.h"

  Resolution::Resolution(){}

  Resolution::~Resolution(){}

  bool Resolution::setTo(__u16 valueX, __u16 valueY){
    
    //this->videoDevice->getVideoFormat()->fmt->pix->height
    
    
 //\ TODO   this->videoDevice->applyChanges('f'); // ioctl call in VideoDevice to apply changes
    
    return true;
  }

  bool Resolution::reset(){
    //\ TODO
    return true;
  }

  char* Resolution::getResolution(){
    //\ TODO
    return 0;
  }
  
  
  // these functions will not be used for this class
  bool Resolution::increase(int value){

    return true;
  }

  bool Resolution::decrease(int value){

    return true;
  }
