/* Generated by Together */

#include "Resolution.h"

  Resolution::Resolution(){}

  Resolution::~Resolution(){}

  bool Resolution::setTo(__u16 valueX, __u16 valueY){
    
    //this->videoDevice->getVideoFormat()->fmt->pix->height
    // to use : VIDIOC_G_FMT and VIDIOC_S_FMT ioclt
    
    return true;
  }

  bool Resolution::reset(){

    return true;
  }

  char* Resolution::getResolution(){

    return 0;
  }
  
  
  // these functions will not be used for this class
  bool Resolution::increase(int value){

    return true;
  }

  bool Resolution::decrease(int value){

    return true;
  }
