/* Generated by Together */

#ifndef VIDEODEVICEMANAGER_H
#define VIDEODEVICEMANAGER_H

#include "Command.h"
#include "Colour.h"
#include "Resolution.h"
#include "Brightness.h"
#include "Capture.h"
#include "Contrast.h"
#include "VideoDevice.h"

enum TCommand{	CONTRAST= 	0x1,
				BRIGHTNESS= 0x2,
				COLOR= 		0x3,
				CAPTURE=	0x4,
				RESOLUTION= 0x5			
				};

//! VideoDeviceManager
/*!
 * This class manages the video device, it make the link between the device and his properties objects (brightness, luminosity...). It also creates the DeviceManger object and it can change it too. Only one instance of the manager can exist at one time
 */
class VideoDeviceManager {
public:


    //! Constructor.
    VideoDeviceManager();


    //! Destructor
    ~VideoDeviceManager();


    //! Method to get a new command (propriety)
    /*!
     * This method creates a new command (a propriety of the video device) and returns a pointer to this command 
     * 
     * \param ref the reference of the command
     * \return a pointer to the created command
     */
    Command* getCommand(TCommand ref);

    //! Method to create a new VideoDevice.
    /*!
     * \param srcName the name of the camera that the new VideoDevice will use as a source.
     * \return the success of the operation
     */
   bool createDevice(char* srcName);


    //! Method to change the VideoDevice.
    /*!
     * \param srcName the pointer to a char array containing the path to the device
     * \return a bool representing the success of the VideoDevice change
     */
    bool changeDevice(char* srcName);


    //! Method to get the instance of the VideoDeviceManager.
    /*!
     * If it does not exist, this method will create it
     * 
     * \return an instance of the VideoDeviceManager
     */
    static VideoDeviceManager* getInstance();

private:

    /** @link dependency */
    /*# Command lnkCommand; */
    //! The instance of the VideoDeviceManager
    static VideoDeviceManager* instance;

    //! The pointer of the actual VideoDevice
    static VideoDevice* actualVideoDevice;

};
#endif //VIDEODEVICEMANAGER_H
