/* Generated by Together */

#include "VideoDevice.h"

  VideoDevice::VideoDevice(char* srcName){
     
    initDevice(srcName);
    openDevice();
  
  }

  VideoDevice::~VideoDevice(){}

  void VideoDevice::initDevice(char* srcName){
    
    // initiate the name (i.e. "/dev/video0" )
    name = new char[strlen(srcName)+1];
    name = srcName;

    // initiate videoCapability, videoFormat and videPicture attributes 
	this->videoCapability = new v4l2_capability;
	this->videoPicture = new video_picture;
	this->videoFormat = new v4l2_format;
	
  }
  
  bool VideoDevice::openDevice(){

	// open the webcam device, like a file, return a file descriptor
	this->fileDescript = open(name, O_RDONLY);
	
	if(fileDescript < 0){
		printf("error, can't open device %s\n", name);	
		return false;	
	}

	// fill the v4l2_capability struct by a ioctl call (control device)
	if(ioctl(fileDescript, VIDIOC_QUERYCAP, videoCapability)==-1){
		printf("error, can't query device's capabilities\n");
		return false;
	}

	// fill the v4l2_format : videoFormat
	videoFormat->type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
	if(ioctl(fileDescript, VIDIOC_G_FMT, videoFormat)==-1){
		printf("error, can't set the capture image format\n");
		return false;
	}
	videoFormat->fmt.pix.pixelformat = V4L2_PIX_FMT_YUV420;

	// fill the video_picture : videoPicture
	if(ioctl(fileDescript, VIDIOCGPICT, videoFormat)==-1){
		printf("error, can't set the capture image format\n");
		return false;
	}

	// return true to indicate the sucess of the operation
    return true;
  }


  bool VideoDevice::applyChanges(unsigned char propType){
  	
  	switch(propType){
  		
  		// p means changes will be applyed to videoPicture attribute : for brightness, colour, contrast
  		case 'p' :
  				if(ioctl(fileDescript, VIDIOCSPICT, this->videoPicture) == -1){
  					return false;
  				}
  				
				break;
	
		// f means changes will be applyed to videoFormat attribute : for resolution and all related proprties
  		case 'f' :
				if(ioctl(fileDescript, VIDIOC_S_FMT, this->videoFormat) == -1){
  					return false;
  				}
  				
				break;
				
/// not sure that we will need the next case --> no need for the moment!!
		// c means changes will be applyed to videoCapability attribute.  
  		/*case 'c' :
  				if(ioctl(fileDescript, TODO , this->videoCapability) == -1){
  					return false;
  				}
				break;*/
  	}
  	
  	return true;
  }


  bool VideoDevice::closeDevice(){

    return true;
  }
  
  v4l2_format* VideoDevice::getVideoFormat(){
    
    return this->videoFormat;
  }
  
  v4l2_capability* VideoDevice::getVideoCapability(){

    return this->videoCapability;
  }
  
  video_picture* VideoDevice::getVideoPicture(){

    return this->videoPicture;
  }
  
  void VideoDevice::setVideoFormat(v4l2_format* videoFormat){

    this->videoFormat = videoFormat;

  }

  void VideoDevice::setVideoCapability(v4l2_capability* videoCapability){

    this->videoCapability = videoCapability;

  }

  void VideoDevice::setVideoPicture(video_picture* videoPicture){

    this->videoPicture = videoPicture;

  }
  
  void VideoDevice::setBrightness(__u16 value){

    this->videoPicture->brightness = value;

  }
  
  void VideoDevice::setContrast(__u16 value){

    this->videoPicture->contrast = value;

  }
  
  void VideoDevice::setColour(__u16 value){

    this->videoPicture->colour = value;

  }
  
  char* VideoDevice::getName(){

    return this->name;
  }

  int VideoDevice::getFileDescript(){

    return this->fileDescript;
  }
