
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__contactmanager_glue_h__ADAPTOR_MARSHAL_H
#define __dbusxx__contactmanager_glue_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>

namespace org {
namespace sflphone {
namespace SFLphone {

class ContactManager
: public ::DBus::InterfaceAdaptor
{
public:

    ContactManager()
    : ::DBus::InterfaceAdaptor("org.sflphone.SFLphone.ContactManager")
    {
        register_method(ContactManager, getContacts, _getContacts_stub);
        register_method(ContactManager, getContactDetails, _getContactDetails_stub);
        register_method(ContactManager, getContactEntries, _getContactEntries_stub);
        register_method(ContactManager, getContactEntryDetails, _getContactEntryDetails_stub);
        register_method(ContactManager, setContacts, _setContacts_stub);
        register_method(ContactManager, setContactEntries, _setContactEntries_stub);
        register_method(ContactManager, setPresence, _setPresence_stub);
    }

    ::DBus::IntrospectedInterface* const introspect() const 
    {
        static ::DBus::IntrospectedArgument getContacts_args[] = 
        {
            { "accountID", "s", true },
            { "contactIDs", "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getContactDetails_args[] = 
        {
            { "accountID", "s", true },
            { "contactID", "s", true },
            { "details", "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getContactEntries_args[] = 
        {
            { "accountID", "s", true },
            { "contactID", "s", true },
            { "contactEntryIDs", "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getContactEntryDetails_args[] = 
        {
            { "accountID", "s", true },
            { "contactID", "s", true },
            { "contactEntryID", "s", true },
            { "details", "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument setContacts_args[] = 
        {
            { "accountID", "s", true },
            { "details", "as", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument setContactEntries_args[] = 
        {
            { "contactID", "s", true },
            { "details", "as", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument setPresence_args[] = 
        {
            { "accountID", "s", true },
            { "presence", "s", true },
            { "additionalInfo", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument contactEntryPresenceChanged_args[] = 
        {
            { "accountID", "s", false },
            { "entryID", "s", false },
            { "presence", "s", false },
            { "additionalInfo", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod ContactManager_methods[] = 
        {
            { "getContacts", getContacts_args },
            { "getContactDetails", getContactDetails_args },
            { "getContactEntries", getContactEntries_args },
            { "getContactEntryDetails", getContactEntryDetails_args },
            { "setContacts", setContacts_args },
            { "setContactEntries", setContactEntries_args },
            { "setPresence", setPresence_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod ContactManager_signals[] = 
        {
            { "contactEntryPresenceChanged", contactEntryPresenceChanged_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty ContactManager_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface ContactManager_interface = 
        {
            "org.sflphone.SFLphone.ContactManager",
            ContactManager_methods,
            ContactManager_signals,
            ContactManager_properties
        };
        return &ContactManager_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual std::vector< ::DBus::String > getContacts( const ::DBus::String& accountID ) = 0;
    virtual std::vector< ::DBus::String > getContactDetails( const ::DBus::String& accountID, const ::DBus::String& contactID ) = 0;
    virtual std::vector< ::DBus::String > getContactEntries( const ::DBus::String& accountID, const ::DBus::String& contactID ) = 0;
    virtual std::vector< ::DBus::String > getContactEntryDetails( const ::DBus::String& accountID, const ::DBus::String& contactID, const ::DBus::String& contactEntryID ) = 0;
    virtual void setContacts( const ::DBus::String& accountID, const std::vector< ::DBus::String >& details ) = 0;
    virtual void setContactEntries( const ::DBus::String& contactID, const std::vector< ::DBus::String >& details ) = 0;
    virtual void setPresence( const ::DBus::String& accountID, const ::DBus::String& presence, const ::DBus::String& additionalInfo ) = 0;

public:

    /* signal emitters for this interface
     */
    void contactEntryPresenceChanged( const ::DBus::String& arg1, const ::DBus::String& arg2, const ::DBus::String& arg3, const ::DBus::String& arg4 )
    {
        ::DBus::SignalMessage sig("contactEntryPresenceChanged");
        ::DBus::MessageIter wi = sig.writer();
        wi << arg1;
        wi << arg2;
        wi << arg3;
        wi << arg4;
        emit_signal(sig);
    }

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _getContacts_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        std::vector< ::DBus::String > argout1 = getContacts(argin1);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _getContactDetails_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        ::DBus::String argin2; ri >> argin2;
        std::vector< ::DBus::String > argout1 = getContactDetails(argin1, argin2);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _getContactEntries_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        ::DBus::String argin2; ri >> argin2;
        std::vector< ::DBus::String > argout1 = getContactEntries(argin1, argin2);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _getContactEntryDetails_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        ::DBus::String argin2; ri >> argin2;
        ::DBus::String argin3; ri >> argin3;
        std::vector< ::DBus::String > argout1 = getContactEntryDetails(argin1, argin2, argin3);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _setContacts_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        std::vector< ::DBus::String > argin2; ri >> argin2;
        setContacts(argin1, argin2);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _setContactEntries_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        std::vector< ::DBus::String > argin2; ri >> argin2;
        setContactEntries(argin1, argin2);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _setPresence_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        ::DBus::String argin2; ri >> argin2;
        ::DBus::String argin3; ri >> argin3;
        setPresence(argin1, argin2, argin3);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

} } } 
#endif//__dbusxx__contactmanager_glue_h__ADAPTOR_MARSHAL_H
