
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__voicemailmanager_glue_h__ADAPTOR_MARSHAL_H
#define __dbusxx__voicemailmanager_glue_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>

namespace org {
namespace sflphone {
namespace SFLphone {

class VoicemailManager
: public ::DBus::InterfaceAdaptor
{
public:

    VoicemailManager()
    : ::DBus::InterfaceAdaptor("org.sflphone.SFLphone.VoicemailManager")
    {
        register_method(VoicemailManager, getListFolders, _getListFolders_stub);
        register_method(VoicemailManager, getFolderCount, _getFolderCount_stub);
        register_method(VoicemailManager, getListMails, _getListMails_stub);
        register_method(VoicemailManager, getVoicemailInfo, _getVoicemailInfo_stub);
        register_method(VoicemailManager, getListErrors, _getListErrors_stub);
        register_method(VoicemailManager, playVoicemail, _playVoicemail_stub);
        register_method(VoicemailManager, stopVoicemail, _stopVoicemail_stub);
        register_method(VoicemailManager, isVoicemailServerEnabled, _isVoicemailServerEnabled_stub);
        register_method(VoicemailManager, voicemailServerEnable, _voicemailServerEnable_stub);
        register_method(VoicemailManager, getVoicemailConfigAddress, _getVoicemailConfigAddress_stub);
        register_method(VoicemailManager, setVoicemailConfigAddress, _setVoicemailConfigAddress_stub);
        register_method(VoicemailManager, getVoicemailConfigPath, _getVoicemailConfigPath_stub);
        register_method(VoicemailManager, setVoicemailConfigPath, _setVoicemailConfigPath_stub);
        register_method(VoicemailManager, getVoicemailConfigPort, _getVoicemailConfigPort_stub);
        register_method(VoicemailManager, setVoicemailConfigPort, _setVoicemailConfigPort_stub);
        register_method(VoicemailManager, isVoicemailConfigHttpsEnabled, _isVoicemailConfigHttpsEnabled_stub);
        register_method(VoicemailManager, voicemailConfigHttpsEnable, _voicemailConfigHttpsEnable_stub);
    }

    ::DBus::IntrospectedInterface* const introspect() const 
    {
        static ::DBus::IntrospectedArgument getListFolders_args[] = 
        {
            { "list", "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getFolderCount_args[] = 
        {
            { "folder", "s", true },
            { "count", "i", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getListMails_args[] = 
        {
            { "folder", "s", true },
            { "list", "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getVoicemailInfo_args[] = 
        {
            { "folder", "s", true },
            { "name", "s", true },
            { "list", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getListErrors_args[] = 
        {
            { "list", "as", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument playVoicemail_args[] = 
        {
            { "folderName", "s", true },
            { "voicemailName", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument stopVoicemail_args[] = 
        {
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument isVoicemailServerEnabled_args[] = 
        {
            { "enabled", "b", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument voicemailServerEnable_args[] = 
        {
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getVoicemailConfigAddress_args[] = 
        {
            { "address", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument setVoicemailConfigAddress_args[] = 
        {
            { "address", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getVoicemailConfigPath_args[] = 
        {
            { "path", "s", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument setVoicemailConfigPath_args[] = 
        {
            { "path", "s", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument getVoicemailConfigPort_args[] = 
        {
            { "port", "i", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument setVoicemailConfigPort_args[] = 
        {
            { "port", "i", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument isVoicemailConfigHttpsEnabled_args[] = 
        {
            { "enabled", "b", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument voicemailConfigHttpsEnable_args[] = 
        {
            { "enabled", "b", true },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument voicemailPlaying_args[] = 
        {
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedArgument voicemailStopped_args[] = 
        {
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod VoicemailManager_methods[] = 
        {
            { "getListFolders", getListFolders_args },
            { "getFolderCount", getFolderCount_args },
            { "getListMails", getListMails_args },
            { "getVoicemailInfo", getVoicemailInfo_args },
            { "getListErrors", getListErrors_args },
            { "playVoicemail", playVoicemail_args },
            { "stopVoicemail", stopVoicemail_args },
            { "isVoicemailServerEnabled", isVoicemailServerEnabled_args },
            { "voicemailServerEnable", voicemailServerEnable_args },
            { "getVoicemailConfigAddress", getVoicemailConfigAddress_args },
            { "setVoicemailConfigAddress", setVoicemailConfigAddress_args },
            { "getVoicemailConfigPath", getVoicemailConfigPath_args },
            { "setVoicemailConfigPath", setVoicemailConfigPath_args },
            { "getVoicemailConfigPort", getVoicemailConfigPort_args },
            { "setVoicemailConfigPort", setVoicemailConfigPort_args },
            { "isVoicemailConfigHttpsEnabled", isVoicemailConfigHttpsEnabled_args },
            { "voicemailConfigHttpsEnable", voicemailConfigHttpsEnable_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod VoicemailManager_signals[] = 
        {
            { "voicemailPlaying", voicemailPlaying_args },
            { "voicemailStopped", voicemailStopped_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty VoicemailManager_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface VoicemailManager_interface = 
        {
            "org.sflphone.SFLphone.VoicemailManager",
            VoicemailManager_methods,
            VoicemailManager_signals,
            VoicemailManager_properties
        };
        return &VoicemailManager_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual std::vector< ::DBus::String > getListFolders(  ) = 0;
    virtual ::DBus::Int32 getFolderCount( const ::DBus::String& folder ) = 0;
    virtual std::vector< ::DBus::String > getListMails( const ::DBus::String& folder ) = 0;
    virtual ::DBus::String getVoicemailInfo( const ::DBus::String& folder, const ::DBus::String& name ) = 0;
    virtual std::vector< ::DBus::String > getListErrors(  ) = 0;
    virtual void playVoicemail( const ::DBus::String& folderName, const ::DBus::String& voicemailName ) = 0;
    virtual void stopVoicemail(  ) = 0;
    virtual ::DBus::Bool isVoicemailServerEnabled(  ) = 0;
    virtual void voicemailServerEnable(  ) = 0;
    virtual ::DBus::String getVoicemailConfigAddress(  ) = 0;
    virtual void setVoicemailConfigAddress( const ::DBus::String& address ) = 0;
    virtual ::DBus::String getVoicemailConfigPath(  ) = 0;
    virtual void setVoicemailConfigPath( const ::DBus::String& path ) = 0;
    virtual ::DBus::Int32 getVoicemailConfigPort(  ) = 0;
    virtual void setVoicemailConfigPort( const ::DBus::Int32& port ) = 0;
    virtual ::DBus::Bool isVoicemailConfigHttpsEnabled(  ) = 0;
    virtual void voicemailConfigHttpsEnable( const ::DBus::Bool& enabled ) = 0;

public:

    /* signal emitters for this interface
     */
    void voicemailPlaying(  )
    {
        ::DBus::SignalMessage sig("voicemailPlaying");
        emit_signal(sig);
    }
    void voicemailStopped(  )
    {
        ::DBus::SignalMessage sig("voicemailStopped");
        emit_signal(sig);
    }

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _getListFolders_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        std::vector< ::DBus::String > argout1 = getListFolders();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _getFolderCount_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        ::DBus::Int32 argout1 = getFolderCount(argin1);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _getListMails_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        std::vector< ::DBus::String > argout1 = getListMails(argin1);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _getVoicemailInfo_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        ::DBus::String argin2; ri >> argin2;
        ::DBus::String argout1 = getVoicemailInfo(argin1, argin2);
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _getListErrors_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        std::vector< ::DBus::String > argout1 = getListErrors();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _playVoicemail_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        ::DBus::String argin2; ri >> argin2;
        playVoicemail(argin1, argin2);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _stopVoicemail_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        stopVoicemail();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _isVoicemailServerEnabled_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Bool argout1 = isVoicemailServerEnabled();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _voicemailServerEnable_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        voicemailServerEnable();
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _getVoicemailConfigAddress_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argout1 = getVoicemailConfigAddress();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _setVoicemailConfigAddress_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        setVoicemailConfigAddress(argin1);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _getVoicemailConfigPath_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argout1 = getVoicemailConfigPath();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _setVoicemailConfigPath_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::String argin1; ri >> argin1;
        setVoicemailConfigPath(argin1);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _getVoicemailConfigPort_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Int32 argout1 = getVoicemailConfigPort();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _setVoicemailConfigPort_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Int32 argin1; ri >> argin1;
        setVoicemailConfigPort(argin1);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
    ::DBus::Message _isVoicemailConfigHttpsEnabled_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Bool argout1 = isVoicemailConfigHttpsEnabled();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
    ::DBus::Message _voicemailConfigHttpsEnable_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        ::DBus::Bool argin1; ri >> argin1;
        voicemailConfigHttpsEnable(argin1);
        ::DBus::ReturnMessage reply(call);
        return reply;
    }
};

} } } 
#endif//__dbusxx__voicemailmanager_glue_h__ADAPTOR_MARSHAL_H
