
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__voicemailmanager_glue_h__ADAPTOR_MARSHAL_H
#define __dbusxx__voicemailmanager_glue_h__ADAPTOR_MARSHAL_H

#include <dbus-c++/dbus.h>

namespace org {
namespace sflphone {
namespace SFLphone {

class VoicemailManager
: public ::DBus::InterfaceAdaptor
{
public:

    VoicemailManager()
    : ::DBus::InterfaceAdaptor("org.sflphone.SFLphone.VoicemailManager")
    {
        register_method(VoicemailManager, listMails, _listMails_stub);
    }

    ::DBus::IntrospectedInterface* const introspect() const 
    {
        static ::DBus::IntrospectedArgument listMails_args[] = 
        {
            { "list", "a{s}", false },
            { 0, 0, 0 }
        };
        static ::DBus::IntrospectedMethod VoicemailManager_methods[] = 
        {
            { "listMails", listMails_args },
            { 0, 0 }
        };
        static ::DBus::IntrospectedMethod VoicemailManager_signals[] = 
        {
            { 0, 0 }
        };
        static ::DBus::IntrospectedProperty VoicemailManager_properties[] = 
        {
            { 0, 0, 0, 0 }
        };
        static ::DBus::IntrospectedInterface VoicemailManager_interface = 
        {
            "org.sflphone.SFLphone.VoicemailManager",
            VoicemailManager_methods,
            VoicemailManager_signals,
            VoicemailManager_properties
        };
        return &VoicemailManager_interface;
    }

public:

    /* properties exposed by this interface, use
     * property() and property(value) to get and set a particular property
     */

public:

    /* methods exported by this interface,
     * you will have to implement them in your ObjectAdaptor
     */
    virtual std::map< ::DBus::String,  > listMails(  ) = 0;

public:

    /* signal emitters for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual interface method)
     */
    ::DBus::Message _listMails_stub( const ::DBus::CallMessage& call )
    {
        ::DBus::MessageIter ri = call.reader();

        std::map< ::DBus::String,  > argout1 = listMails();
        ::DBus::ReturnMessage reply(call);
        ::DBus::MessageIter wi = reply.writer();
        wi << argout1;
        return reply;
    }
};

} } } 
#endif//__dbusxx__voicemailmanager_glue_h__ADAPTOR_MARSHAL_H
