/* Generated by dbus-binding-tool; do not edit! */

#include <glib/gtypes.h>
#include <glib/gerror.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_sflphone_SFLphone_VoicemailManager
#define DBUS_GLIB_CLIENT_WRAPPERS_org_sflphone_SFLphone_VoicemailManager

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_open_connection (DBusGProxy *proxy, gboolean* OUT_opening, GError **error)

{
  return dbus_g_proxy_call (proxy, "openConnection", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, OUT_opening, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_open_connection_reply) (DBusGProxy *proxy, gboolean OUT_opening, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_open_connection_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gboolean OUT_opening;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_BOOLEAN, &OUT_opening, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_open_connection_reply)data->cb) (proxy, OUT_opening, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_open_connection_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_open_connection_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "openConnection", org_sflphone_SFLphone_VoicemailManager_open_connection_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_close_connection (DBusGProxy *proxy, gboolean* OUT_closing, GError **error)

{
  return dbus_g_proxy_call (proxy, "closeConnection", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, OUT_closing, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_close_connection_reply) (DBusGProxy *proxy, gboolean OUT_closing, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_close_connection_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gboolean OUT_closing;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_BOOLEAN, &OUT_closing, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_close_connection_reply)data->cb) (proxy, OUT_closing, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_close_connection_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_close_connection_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "closeConnection", org_sflphone_SFLphone_VoicemailManager_close_connection_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_get_list_folders (DBusGProxy *proxy, char *** OUT_list, GError **error)

{
  return dbus_g_proxy_call (proxy, "getListFolders", error, G_TYPE_INVALID, G_TYPE_STRV, OUT_list, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_get_list_folders_reply) (DBusGProxy *proxy, char * *OUT_list, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_get_list_folders_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char ** OUT_list;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRV, &OUT_list, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_get_list_folders_reply)data->cb) (proxy, OUT_list, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_get_list_folders_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_get_list_folders_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "getListFolders", org_sflphone_SFLphone_VoicemailManager_get_list_folders_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_get_folder_count (DBusGProxy *proxy, const char * IN_folder, gint* OUT_count, GError **error)

{
  return dbus_g_proxy_call (proxy, "getFolderCount", error, G_TYPE_STRING, IN_folder, G_TYPE_INVALID, G_TYPE_INT, OUT_count, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_get_folder_count_reply) (DBusGProxy *proxy, gint OUT_count, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_get_folder_count_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_count;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_count, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_get_folder_count_reply)data->cb) (proxy, OUT_count, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_get_folder_count_async (DBusGProxy *proxy, const char * IN_folder, org_sflphone_SFLphone_VoicemailManager_get_folder_count_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "getFolderCount", org_sflphone_SFLphone_VoicemailManager_get_folder_count_async_callback, stuff, g_free, G_TYPE_STRING, IN_folder, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_get_list_mails (DBusGProxy *proxy, const char * IN_folder, char *** OUT_list, GError **error)

{
  return dbus_g_proxy_call (proxy, "getListMails", error, G_TYPE_STRING, IN_folder, G_TYPE_INVALID, G_TYPE_STRV, OUT_list, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_get_list_mails_reply) (DBusGProxy *proxy, char * *OUT_list, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_get_list_mails_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char ** OUT_list;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRV, &OUT_list, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_get_list_mails_reply)data->cb) (proxy, OUT_list, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_get_list_mails_async (DBusGProxy *proxy, const char * IN_folder, org_sflphone_SFLphone_VoicemailManager_get_list_mails_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "getListMails", org_sflphone_SFLphone_VoicemailManager_get_list_mails_async_callback, stuff, g_free, G_TYPE_STRING, IN_folder, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_get_voicemail_info (DBusGProxy *proxy, const char * IN_folder, const char * IN_name, char ** OUT_list, GError **error)

{
  return dbus_g_proxy_call (proxy, "getVoicemailInfo", error, G_TYPE_STRING, IN_folder, G_TYPE_STRING, IN_name, G_TYPE_INVALID, G_TYPE_STRING, OUT_list, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_get_voicemail_info_reply) (DBusGProxy *proxy, char * OUT_list, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_get_voicemail_info_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_list;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_list, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_get_voicemail_info_reply)data->cb) (proxy, OUT_list, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_get_voicemail_info_async (DBusGProxy *proxy, const char * IN_folder, const char * IN_name, org_sflphone_SFLphone_VoicemailManager_get_voicemail_info_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "getVoicemailInfo", org_sflphone_SFLphone_VoicemailManager_get_voicemail_info_async_callback, stuff, g_free, G_TYPE_STRING, IN_folder, G_TYPE_STRING, IN_name, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_get_list_errors (DBusGProxy *proxy, char *** OUT_list, GError **error)

{
  return dbus_g_proxy_call (proxy, "getListErrors", error, G_TYPE_INVALID, G_TYPE_STRV, OUT_list, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_get_list_errors_reply) (DBusGProxy *proxy, char * *OUT_list, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_get_list_errors_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char ** OUT_list;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRV, &OUT_list, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_get_list_errors_reply)data->cb) (proxy, OUT_list, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_get_list_errors_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_get_list_errors_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "getListErrors", org_sflphone_SFLphone_VoicemailManager_get_list_errors_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_play_voicemail (DBusGProxy *proxy, const char * IN_folderName, const char * IN_voicemailName, GError **error)

{
  return dbus_g_proxy_call (proxy, "playVoicemail", error, G_TYPE_STRING, IN_folderName, G_TYPE_STRING, IN_voicemailName, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_play_voicemail_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_play_voicemail_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_play_voicemail_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_play_voicemail_async (DBusGProxy *proxy, const char * IN_folderName, const char * IN_voicemailName, org_sflphone_SFLphone_VoicemailManager_play_voicemail_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "playVoicemail", org_sflphone_SFLphone_VoicemailManager_play_voicemail_async_callback, stuff, g_free, G_TYPE_STRING, IN_folderName, G_TYPE_STRING, IN_voicemailName, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_stop_voicemail (DBusGProxy *proxy, GError **error)

{
  return dbus_g_proxy_call (proxy, "stopVoicemail", error, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_stop_voicemail_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_stop_voicemail_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_stop_voicemail_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_stop_voicemail_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_stop_voicemail_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "stopVoicemail", org_sflphone_SFLphone_VoicemailManager_stop_voicemail_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_is_voicemail_server_enabled (DBusGProxy *proxy, gboolean* OUT_enabled, GError **error)

{
  return dbus_g_proxy_call (proxy, "isVoicemailServerEnabled", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, OUT_enabled, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_is_voicemail_server_enabled_reply) (DBusGProxy *proxy, gboolean OUT_enabled, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_is_voicemail_server_enabled_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gboolean OUT_enabled;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_BOOLEAN, &OUT_enabled, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_is_voicemail_server_enabled_reply)data->cb) (proxy, OUT_enabled, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_is_voicemail_server_enabled_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_is_voicemail_server_enabled_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "isVoicemailServerEnabled", org_sflphone_SFLphone_VoicemailManager_is_voicemail_server_enabled_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_voicemail_server_enable (DBusGProxy *proxy, GError **error)

{
  return dbus_g_proxy_call (proxy, "voicemailServerEnable", error, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_voicemail_server_enable_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_voicemail_server_enable_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_voicemail_server_enable_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_voicemail_server_enable_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_voicemail_server_enable_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "voicemailServerEnable", org_sflphone_SFLphone_VoicemailManager_voicemail_server_enable_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_address (DBusGProxy *proxy, char ** OUT_address, GError **error)

{
  return dbus_g_proxy_call (proxy, "getVoicemailConfigAddress", error, G_TYPE_INVALID, G_TYPE_STRING, OUT_address, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_address_reply) (DBusGProxy *proxy, char * OUT_address, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_address_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_address;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_address, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_address_reply)data->cb) (proxy, OUT_address, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_address_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_address_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "getVoicemailConfigAddress", org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_address_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_address (DBusGProxy *proxy, const char * IN_address, GError **error)

{
  return dbus_g_proxy_call (proxy, "setVoicemailConfigAddress", error, G_TYPE_STRING, IN_address, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_address_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_address_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_address_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_address_async (DBusGProxy *proxy, const char * IN_address, org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_address_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "setVoicemailConfigAddress", org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_address_async_callback, stuff, g_free, G_TYPE_STRING, IN_address, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_path (DBusGProxy *proxy, char ** OUT_path, GError **error)

{
  return dbus_g_proxy_call (proxy, "getVoicemailConfigPath", error, G_TYPE_INVALID, G_TYPE_STRING, OUT_path, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_path_reply) (DBusGProxy *proxy, char * OUT_path, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_path_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_path;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_path, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_path_reply)data->cb) (proxy, OUT_path, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_path_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_path_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "getVoicemailConfigPath", org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_path_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_path (DBusGProxy *proxy, const char * IN_path, GError **error)

{
  return dbus_g_proxy_call (proxy, "setVoicemailConfigPath", error, G_TYPE_STRING, IN_path, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_path_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_path_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_path_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_path_async (DBusGProxy *proxy, const char * IN_path, org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_path_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "setVoicemailConfigPath", org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_path_async_callback, stuff, g_free, G_TYPE_STRING, IN_path, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_port (DBusGProxy *proxy, gint* OUT_port, GError **error)

{
  return dbus_g_proxy_call (proxy, "getVoicemailConfigPort", error, G_TYPE_INVALID, G_TYPE_INT, OUT_port, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_port_reply) (DBusGProxy *proxy, gint OUT_port, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_port_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_port;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_port, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_port_reply)data->cb) (proxy, OUT_port, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_port_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_port_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "getVoicemailConfigPort", org_sflphone_SFLphone_VoicemailManager_get_voicemail_config_port_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_port (DBusGProxy *proxy, const gint IN_port, GError **error)

{
  return dbus_g_proxy_call (proxy, "setVoicemailConfigPort", error, G_TYPE_INT, IN_port, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_port_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_port_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_port_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_port_async (DBusGProxy *proxy, const gint IN_port, org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_port_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "setVoicemailConfigPort", org_sflphone_SFLphone_VoicemailManager_set_voicemail_config_port_async_callback, stuff, g_free, G_TYPE_INT, IN_port, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_is_voicemail_config_https_enabled (DBusGProxy *proxy, gboolean* OUT_enabled, GError **error)

{
  return dbus_g_proxy_call (proxy, "isVoicemailConfigHttpsEnabled", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, OUT_enabled, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_is_voicemail_config_https_enabled_reply) (DBusGProxy *proxy, gboolean OUT_enabled, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_is_voicemail_config_https_enabled_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gboolean OUT_enabled;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_BOOLEAN, &OUT_enabled, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_is_voicemail_config_https_enabled_reply)data->cb) (proxy, OUT_enabled, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_is_voicemail_config_https_enabled_async (DBusGProxy *proxy, org_sflphone_SFLphone_VoicemailManager_is_voicemail_config_https_enabled_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "isVoicemailConfigHttpsEnabled", org_sflphone_SFLphone_VoicemailManager_is_voicemail_config_https_enabled_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_sflphone_SFLphone_VoicemailManager_voicemail_config_https_enable (DBusGProxy *proxy, const gboolean IN_enabled, GError **error)

{
  return dbus_g_proxy_call (proxy, "voicemailConfigHttpsEnable", error, G_TYPE_BOOLEAN, IN_enabled, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_sflphone_SFLphone_VoicemailManager_voicemail_config_https_enable_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_sflphone_SFLphone_VoicemailManager_voicemail_config_https_enable_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_sflphone_SFLphone_VoicemailManager_voicemail_config_https_enable_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_sflphone_SFLphone_VoicemailManager_voicemail_config_https_enable_async (DBusGProxy *proxy, const gboolean IN_enabled, org_sflphone_SFLphone_VoicemailManager_voicemail_config_https_enable_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "voicemailConfigHttpsEnable", org_sflphone_SFLphone_VoicemailManager_voicemail_config_https_enable_async_callback, stuff, g_free, G_TYPE_BOOLEAN, IN_enabled, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_sflphone_SFLphone_VoicemailManager */

G_END_DECLS
